### ISSUE TITLE
Function moodleform_mod::add_intro_editor() is deprecated

### ISSUE THREAD

**Issue by marcusgreen** [ULCC/open-mod_coursework#1]
Nice plugin!. I have installed this plugin on XAMPP under windows for Moodle 3.0 and it shows no platform specific error after some trivial exploration. However it did show the error

Function moodleform_mod::add_intro_editor() is deprecated
I fixed this by replacing 

`$this->add_intro_editor(true, get_string('description', 'coursework'));`
with 
`$this->standard_intro_elements(get_string('description', 'coursework'));`

Around Line 51 of mod_form.php

**Comment by aspark21** [comment]
This was fixed in v16.09.23 / 16be184
