### ISSUE TITLE
Coursework due dates do not set calendar events

### ISSUE THREAD

**Issue by tonydelahunty** [ULCC/open-mod_coursework#12]
More a comment than a bug, but other Moodle activities, notably Assignments from which Coursework is adapted, set calendar events for students when assignments are due. So students might well expect to see these listed on their Dashboard, or in Upcoming events blocks. But Coursework does not set these.

Presumably the Coursework code could easily use the same functions as Assignment to do this (and perhaps allow this option to be toggled off in admin settings).

**Comment by aspark21** [comment]
Hi Tony,

Coursework deadlines do absolutely go into the Calendar. 
![screen shot 2018-04-23 at 12 32 41](https://user-images.githubusercontent.com/4015496/39124201-7886d03a-46f2-11e8-8426-4009d457a983.png)

Upcoming events probably has a timeframe limit to them so if your deadline is in 3 months and upcoming events only shows the next 2 weeks, then that is a limit with that block.



N.B. Coursework isn't a fork of assignment.

**Comment by tonydelahunty** [comment]
Hi Alistair, apologies for the false alarm, and thanks for the speedy response.  That's good to know that it works as one would expect, so feel free to close the issue.  

I did test it in 2 different Moodle instances here, including a fresh installation, but evidently there's some local settings or timings I had overlooked, so I'm sure we will get to the bottom of our issue eventually.
