### ISSUE TITLE
Turnitin EULA check accessing incorrect table

### ISSUE THREAD

**Issue by thepurpleblob** [ULCC/open-mod_coursework#20]
When a user accepts the Turnitin EULA this is written in their record in the table mdl_plagiarism_turnitin_user.

However, in the function has_user_seen_tii_EULA_agreement() in lib.php the SQL checks the table mdl_turnintooltwo_users for acceptance of the agreement. Unless the site happens to have been using both methods to access Turnitin this will always return false. 

The code is checking the wrong table. 

The result of this is that coursework does not work with Turnitin enabled for the activity. 

The link to accept the EULA is shown correctly and then no button at all is displayed to allow the student to submit work.

**Comment by aspark21** [comment]
Technically that was the correct thing to check prior to the plagiarism plugin's version v2019050201 which removed it's reliance on the turnitintooltwo mod plugin. So need to add a condition based on the version of the plagiarism plugin

https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/CHANGELOG.md#release----v2019050201

**Comment by thepurpleblob** [comment]
Is there any update on this? I had a note saying that a new version was pending that will address this.
