### ISSUE TITLE
"float: left" property in .urlselect div causes layout problems in Moodle assignments

### ISSUE THREAD

**Issue by porcospino** [ULCC/open-mod_coursework#5]
In styles.css you have

```
.urlselect div{
    float:left;
}
```
It looks as though you want these divs to float so that you can have "Grading action" and "Showing" on the same line when viewing an instance of mod_coursework.

But the CSS selector is insufficiently precise.  Navigate to an instance of mod_assign and click "View all submissions".  You will notice that the select element labelled "Grading action" also has `float: left` applied, and this messes up the layout of the grading table.

**Comment by aspark21** [comment]
@porcospino have you got some screenshots of this?

**Comment by porcospino** [comment]
Hi @aspark21 

This is the assignment as it appears when the above CSS is included

![float_left](https://cloud.githubusercontent.com/assets/4367303/20978081/6fafe958-bc9f-11e6-978f-c28cc36c87f5.png)

This is the same assignment when I comment out the `.urlselect div` CSS stanza and purge the theme cache.

![float_left_disabled](https://cloud.githubusercontent.com/assets/4367303/20978082/6fb045c4-bc9f-11e6-95f2-9ded9829905c.png)

**Comment by aspark21** [comment]
I see.
Had a look at the impact on Coursework itself which seems pretty minimal:

With it:
![screen shot 2016-12-07 at 17 40 17](https://cloud.githubusercontent.com/assets/4015496/20979293/4b6cffa4-bca4-11e6-9547-8b42415f5670.png)

Without it:

![screen shot 2016-12-07 at 17 39 01](https://cloud.githubusercontent.com/assets/4015496/20979297/51b6f23e-bca4-11e6-9691-1201ce9a0711.png)

**Comment by aferenz** [comment]
fixed in v17.06.01
