### ISSUE TITLE
Unable to install on MoodleWindowsInstaller-latest-33

### ISSUE THREAD

**Issue by Aaranaw** [ULCC/open-mod_coursework#6]
Hi, running a development version of Moodle to test plugins, etc. I have tried to install coursework via the install plugins using a zip file method available in the site administrator window, however it throws the error

**Install plugin from ZIP file
Validating mod_coursework ... 
core_plugin/corrupted_archive_structure**

I have downloaded the file a few times to make sure it did not get corrupted during the download but thats not resolved the issue, and the "more info" button on the error page points to a url that no longer exists http://docs.moodle.org/33/en/error/core_plugin/corrupted_archive_structure

Any help resolving this would be appreciated

**Comment by aferenz** [comment]
Hi Aaranaw, 

Please make sure you have all coursework files (the correct version) zipped in folder called 'mod_coursework'. 
I have installed this today on Moodle 3.3 using zip without any problems. If this doesn't work, have a go at installing it by placing the 'coursework' folder in 'mod' directory and see if you get any errors.

Aleks


![coursework from zip](https://user-images.githubusercontent.com/1838118/32954419-f2f21c4e-cbaa-11e7-93da-dd8b52978884.PNG)

**Comment by Aaranaw** [comment]
Yep that worked, thanks.

**Comment by aferenz** [comment]
You're welcome
