### ISSUE TITLE
Support request, format of Allocated assessors csv file.

### ISSUE THREAD

**Issue by Aaranaw** [ULCC/open-mod_coursework#7]
Hi, I have tried creating a csv file using the format Student,Assessor1,Assessor2 for example
Ben Jones,David Starkey,Sam Smith

This however does not work, it does not say there are any errors once the csv has been uploaded in the Allocate assessors page but it is not assigning David and Sam as the assessors to Ben.

If you could let me have an example csv for this I would be grateful.

Thank you.

**Comment by tworthington** [comment]
Aaran,
   Have you tried using the Moodle usernames rather than their "human" names? I'll check when I get into work tomorrow, but I think that's where you're going wrong.

Thomas

**Comment by Aaranaw** [comment]
I will get that a try and let you know, thanks.

**Comment by Aaranaw** [comment]
That resolved the issue thanks
